import type {Metadata} from "next";
import {Bricolage_Grotesque, Geist, Geist_Mono, Host_Grotesk} from "next/font/google";
import "./globals.scss";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const hostGroteskSans = Host_Grotesk({
  variable: "--font-host-grotesk-sans",
  subsets: ["latin"],
});

const bricolagueGrotesqueSans = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Webique Agency",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${hostGroteskSans.variable} ${geistMono.variable} antialiased`}>
      <main>
        <Navbar/>
        {children}
      </main>
      <Footer/>
      </body>
      </html>
  );
}
