import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import Navbar from "@/app/components/Navbar";
import LenisScrollProvider from "@/app/providers/Lenis";
import Footer from "@/app/components/footer/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const bricolagueGrotesqueSans = Geist({
	variable: "--font-bricolage-grotesque-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Webique Agency",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={`${geistSans.variable} ${bricolagueGrotesqueSans.variable} ${geistMono.variable} antialiased`}>
		<LenisScrollProvider>
			<main>
				<Navbar/>
				{children}
			</main>
			<Footer/>
		</LenisScrollProvider>
		</body>
		</html>
	);
}
