import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import Navbar from "@/app/components/Navbar";
import LenisScrollProvider from "@/app/providers/Lenis";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Webique Agency",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <main className="lg:w-[1360px] max-[1025px]:px-8 mx-auto">
            <LenisScrollProvider>
                <Navbar/>
                {children}
            </LenisScrollProvider>
        </main>
        </body>
        </html>
    );
}
